name: "@meowmeres 🏳️WHITE LISTS🏳️"

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download VPN list
        run: |
          curl -fLsS -o original.txt https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_lite.txt
      # =========================
      # AUTO DETECT CHANGES
      # =========================
      - name: Check updates (auto detect)
        id: check
        run: |
          NEW_HASH=$(sha256sum original.txt | cut -d' ' -f1)

          if [ -f last_hash.txt ]; then
            OLD_HASH=$(cat last_hash.txt)
          else
            OLD_HASH=""
          fi

          if [ "$NEW_HASH" = "$OLD_HASH" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

          echo $NEW_HASH > last_hash.txt

      # если нет изменений — стопаем workflow
      - name: Skip if no changes
        if: steps.check.outputs.changed == 'false'
        run: |
          echo "No changes → skipping build"
          exit 0

      - name: Build VPN file (MSK time)
        run: |
          export TZ=Europe/Moscow

          grep -v '^#' original.txt | grep -v '^$' > clean.txt

          COUNT=$(wc -l < clean.txt)
          DATE=$(date +"%d.%m.%Y")
          TIME=$(date +"%H:%M")

          mkdir -p public

          {
            echo "# profile-title: @meowmeres 🏳️WHITE LISTS🏳️"
            echo "# compatible: Happ / V2rayTun"
            echo "# update: $DATE $TIME (MSK)"
            echo "# servers: $COUNT"
            echo ""

            cat clean.txt

          } > public/white-list.txt

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
